import type { GeneratedPaper } from '../types/assessment';

const DIFFICULTY_COLORS: Record<string, string> = {
  easy: '#059669',
  medium: '#d97706',
  hard: '#dc2626',
};

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function renderPaperHtml(paper: GeneratedPaper, studentInfo?: {
  name?: string;
  rollNumber?: string;
  section?: string;
}): string {
  const sectionsHtml = paper.sections
    .map(
      (sec) => `
      <div class="section">
        <h2 class="section-title">${escapeHtml(sec.title)}</h2>
        <p class="section-instruction">${escapeHtml(sec.instruction)}</p>
        ${sec.questions
          .map(
            (q, i) => `
          <div class="question">
            <div class="question-header">
              <span class="q-num">Q${i + 1}.</span>
              <span class="difficulty" style="background:${DIFFICULTY_COLORS[q.difficulty] || '#666'}">${q.difficulty}</span>
              <span class="marks">[${q.marks} marks]</span>
            </div>
            <p class="q-text">${escapeHtml(q.text)}</p>
            ${
              q.options?.length
                ? `<ul class="options">${q.options.map((o) => `<li>${escapeHtml(o)}</li>`).join('')}</ul>`
                : '<div class="answer-space"></div>'
            }
          </div>`
          )
          .join('')}
      </div>`
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Times New Roman', Georgia, serif; padding: 40px; color: #1a1a1a; font-size: 12pt; }
    .header { text-align: center; border-bottom: 2px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 24px; }
    .header h1 { font-size: 18pt; margin-bottom: 4px; }
    .header .meta { font-size: 11pt; color: #444; }
    .student-info { display: grid; grid-template-columns: 1fr 1fr; gap: 12px 24px; margin-bottom: 28px; }
    .field { border-bottom: 1px solid #333; padding-bottom: 4px; }
    .field label { font-size: 9pt; color: #666; display: block; }
    .section { margin-bottom: 28px; page-break-inside: avoid; }
    .section-title { font-size: 13pt; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-bottom: 6px; }
    .section-instruction { font-style: italic; font-size: 10pt; color: #555; margin-bottom: 14px; }
    .question { margin-bottom: 18px; }
    .question-header { display: flex; align-items: center; gap: 8px; margin-bottom: 6px; }
    .q-num { font-weight: bold; }
    .difficulty { color: white; font-size: 8pt; padding: 2px 8px; border-radius: 4px; text-transform: capitalize; }
    .marks { margin-left: auto; font-size: 10pt; }
    .q-text { line-height: 1.5; margin-bottom: 8px; }
    .options { list-style: upper-alpha; margin-left: 24px; }
    .options li { margin-bottom: 4px; }
    .answer-space { height: 48px; border-bottom: 1px dotted #ccc; margin-top: 8px; }
    .footer { margin-top: 32px; text-align: center; font-size: 9pt; color: #888; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(paper.title)}</h1>
    <p class="meta">${escapeHtml(paper.subject)} · Total Marks: ${paper.totalMarks}</p>
  </div>
  <div class="student-info">
    <div class="field"><label>Name</label>${escapeHtml(studentInfo?.name || '')}</div>
    <div class="field"><label>Roll Number</label>${escapeHtml(studentInfo?.rollNumber || '')}</div>
    <div class="field"><label>Section</label>${escapeHtml(studentInfo?.section || '')}</div>
    <div class="field"><label>Date</label>_______________</div>
  </div>
  ${sectionsHtml}
  <div class="footer">Generated by VedaAI Assessment Creator</div>
</body>
</html>`;
}

export async function generatePdfBuffer(
  paper: GeneratedPaper,
  studentInfo?: { name?: string; rollNumber?: string; section?: string }
): Promise<Buffer> {
  const puppeteer = await import('puppeteer');
  const browser = await puppeteer.default.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(renderPaperHtml(paper, studentInfo), { waitUntil: 'networkidle0' });
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
    });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}
